export const GAMEINTRO = {
    Logo9k: require('../assets/images/pages/game-intro/logo-9k.png'),
    LogoAllbet: require('../assets/images/pages/game-intro/logo-allbet.png'),
    LogoBetter: require('../assets/images/pages/game-intro/logo-better.png'),
    LogoBNG: require('../assets/images/pages/game-intro/logo-bng.png'),
    LogoBoheaven: require('../assets/images/pages/game-intro/logo-boheaven.png'),
    LogoChessCard: require('../assets/images/pages/game-intro/logo-chess-card.png'),
    LogoDG: require('../assets/images/pages/game-intro/logo-dg.png'),
    LogoDreamTech: require('../assets/images/pages/game-intro/logo-dt.png'),
    LogoGoPlay: require('../assets/images/pages/game-intro/logo-play-go.png'),
    LogoOB6: require('../assets/images/pages/game-intro/logo-ob-6.png'),
    LogoOB: require('../assets/images/pages/game-intro/logo-ob.png'),
    LogoOG: require('../assets/images/pages/game-intro/logo-og.png'),
    LogoRTG: require('../assets/images/pages/game-intro/logo-rtg.png'),
    LogoElectronic: require('../assets/images/pages/game-intro/logo-sp.png'),
    LogoSuperLottery: require('../assets/images/pages/game-intro/logo-super-lottery.png'),
    LogoSupperSports: require('../assets/images/pages/game-intro/logo-super-sports.png'),
    LogoWM: require('../assets/images/pages/game-intro/logo-wm.png'),
    LogoSA: require('../assets/images/pages/game-intro/logo-sa.png'),
}