export const configRoutes = {
    home: '/',
    discount: '/discount',
    login: '/login',
    register: '/register',
    blogsport: '/blog-sport',
    invitefriends: '/profile/invite-friends',
    gameIntroduction: '/game-introduction',
    allbet:'/allbet',
    dreamgame:'/dreamgame',
    sagaming: '/sagaming',
    wm: '/wm',
    ob:'/ob',
    betsport:'/betsport',
    super: '/super',
    superg: '/superg',
    lottery:'/lottery',
    dreamtech:'/dreamtech',
    bng: '/BNG',
    profile: '/profile',
    customerService: '/customer-service',
    notificationCenter: '/notification'
}